### preset
include_hp: dcft/train/hp_settings/simpo.yaml

### model
model_name_or_path: "google/gemma-2-9b-it"
resume_from_checkpoint: 'experiments/train/checkpoints/gemma-simpo-reproductions/checkpoint-442'
### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
per_device_eval_batch_size: 1

### dataset
dataset: mlfoundations-dev/gemma2-ultrafeedback-armorm
dataset_dir: ONLINE
template: gemma
formatting: sharegpt
ranking: true
messages: conversations
chosen: chosen
rejected: rejected

### output
output_dir: "experiments/train/checkpoints/gemma-simpo-reproductions"

## reporting
report_to: wandb
run_name: gemma-simpo-reproduction
push_to_db: true
push_to_hub: true
hub_model_id: mlfoundations-dev/gemma-simpo-reproduction
