### model
model_name_or_path: mistralai/Mistral-7B-v0.1

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: dcft/train/zero1.json
packing: true
neat_packing: true
enable_liger_kernel: true

### dataset
dataset: llamafactory/alpaca_en
dataset_dir: ONLINE
template: alpaca
formatting: alpaca
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 16

### output
# save_strategy: "no"
save_strategy: epoch
output_dir: experiments/train/checkpoints/mistral_alpaca_sft_sample
logging_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
gradient_checkpointing: true
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
report_to: wandb
run_name: mistral_alpaca_sft_sample

### eval
# eval_strategy: no
eval_strategy: epoch
val_size: 0.05
push_to_db: true
push_to_hub: true
hub_model_id: mlfoundations-dev/mistral_alpaca_sft_sample