model: eval/sagemaker_scripts/configs/model_configs/open_lm_1b_old.json
checkpoint: /opt/ml/input/data/model/open_lm_1b.pt
eval-yaml: eval/heavy.yaml
output-file: /opt/ml/output/data/open_lm_1b_hf_heavy.yaml
donot-compute-perplexity: ""
config: eval/params.txt