name: isort

on: [push, pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install isort
        run: |
          python -m pip install isort==5.12.0
      - name: Run isort
        run: |
          isort --profile=black --line-length=120 --check .